//
//  ImagesCollectionRouter.swift
//  MarsWatch
//
//  Created by BRQ on 25/04/19.
//  Copyright (c) 2019 BarbaRuiva. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ImagesCollectionRoutingLogic
{
  func routeToDetails(segue: UIStoryboardSegue?)
}

protocol ImagesCollectionDataPassing
{
  var dataStore: ImagesCollectionDataStore? { get }
}

class ImagesCollectionRouter: NSObject, ImagesCollectionRoutingLogic, ImagesCollectionDataPassing
{
  weak var viewController: ImagesCollectionViewController?
  var dataStore: ImagesCollectionDataStore?
  
  // MARK: Routing
    
    func routeToDetails(segue: UIStoryboardSegue?) {
      let storyboard = UIStoryboard(name: "Main", bundle: nil)
      let destinationVC = storyboard.instantiateViewController(withIdentifier: "ImageDetailsViewController") as! ImageDetailsViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
      navigateToSomewhere(source: viewController!, destination: destinationVC)
    
  }

  // MARK: Navigation
  
  func navigateToSomewhere(source: ImagesCollectionViewController, destination: ImageDetailsViewController)
  {
    source.show(destination, sender: nil)
  }

  // MARK: Passing data
  
  func passDataToSomewhere(source: ImagesCollectionDataStore, destination: inout ImageDetailsDataStore)
  {
    destination.cameraName = source.image
    destination.imgSrc = source.imgSrc
  }
}
