//
//  ImagesCollectionWorker.swift
//  MarsWatch
//
//  Created by BRQ on 25/04/19.
//  Copyright (c) 2019 BarbaRuiva. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import PromiseKit

class ImagesCollectionWorker
{
    func getPhotos() -> Promise<[Photo]>{
        return Webservice.GetPhotos.getMarsPhotos()
  }
}
