//
//  ImagesCollectionModels.swift
//  MarsWatch
//
//  Created by BRQ on 25/04/19.
//  Copyright (c) 2019 BarbaRuiva. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ImagesCollection
{
  // MARK: Use cases
    
    enum Photos {
        struct Request { }
        
        struct Response {
            struct Success {
                let photos: [Photo]
            }
            
            struct Failure {
                let error: Error
            }
        }
        
        struct ViewModel {
            struct PhotosDisplay {
                let camera: PhotoCamera?    
                let imgSrc: String?
            }
            
            struct Success {
                let items: [PhotosDisplay]
            }
            
            struct Failure {
                let message: String
            }
            
        }
    }
}
