//
//  ImageDetailsViewController.swift
//  MarsWatch
//
//  Created by BRQ on 26/04/19.
//  Copyright (c) 2019 BarbaRuiva. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ImageDetailsDisplayLogic: class
{
  func displaySomething(viewModel: ImageDetails.ShowImage.ViewModel)
}

class ImageDetailsViewController: UIViewController, ImageDetailsDisplayLogic
{
  var interactor: ImageDetailsBusinessLogic?
  var router: (NSObjectProtocol & ImageDetailsRoutingLogic & ImageDetailsDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = ImageDetailsInteractor()
    let presenter = ImageDetailsPresenter()
    let router = ImageDetailsRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
  }
  
  // MARK: Do something
  
  @IBOutlet weak var nameTextField: UILabel!
  @IBOutlet weak var imgDetails: UIImageView!
    
  func doSomething()
  {
    let request = ImageDetails.ShowImage.Request()
    interactor?.showDetails(request: request)
  }
  
  func displaySomething(viewModel: ImageDetails.ShowImage.ViewModel)
  {
    nameTextField.text = viewModel.cameraName?.capitalized
    imgDetails.sd_setImage(with: URL(string: viewModel.imgSrc!), placeholderImage: UIImage(named: "placeholder"))
  }
}
