//
//  ImageDetailsModels.swift
//  MarsWatch
//
//  Created by BRQ on 26/04/19.
//  Copyright (c) 2019 BarbaRuiva. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ImageDetails
{
  // MARK: Use cases
  
  enum ShowImage
  {
    struct Request
    {
    }
    struct Response
    {
        var imgSrc: String?
        var cameraName: String?
    }
    struct ViewModel
    {
        var imgSrc: String?
        var cameraName: String?
    }
  }
}
